### ISSUE TITLE
`fiffs_write` doesn't truncate file

### ISSUE THREAD

**Issue by blackwer** [blackwer/FIFFS#3]
```
% echo moo > mnt/foo
% cat mnt/foo
moo
at
```

See documentation in `fuse_lowlevel.h` `void (*open)`. We likely just need to properly truncate the file when opened in write mode vs append mode.

**Comment by alexdotc** [comment]
I will work on this as a way to familiarize myself with fuse

**Comment by blackwer** [comment]
sounds good! i think the info you need will be in the fuse file handle info struct.

**Comment by blackwer** [comment]
Fixed by properly handling get/setattr
