### ISSUE TITLE
Figure out inode logic/multiple directories

### ISSUE THREAD

**Issue by blackwer** [blackwer/FIFFS#4]
Currently the connection between fuse inodes and how those are represented in memory are completely distinct. This is just a hack to get things working. Ideally an inode would actually store all the relevant stuff about the inode, and not just kinda hack the two systems together. This is partly why there is no unlinking and only a single directory.

I'm just mostly delaying this until we really start thinking about multi-node mounts. But getting these data structures correct will be core.

**Comment by alexdotc** [comment]
#5
